{
 "title": "Gatling Report",
 "description": "Gatling dashboard with parameters: granularity (1s, 5s, ...) and request filter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "simulation",
    "label": "simulation",
    "query": "SHOW TAG VALUES WITH KEY = \"simulation\""
   },
   {
    "name": "request",
    "label": "request",
    "query": "SHOW TAG VALUES WITH KEY = \"request\""
   },
   {
    "name": "g",
    "label": "granularity",
    "query": "1s,5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Users",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_simulation",
     "groupBy": [
      { "params": [ "$g" ], "type": "time" }
     ],
     "measurement": "gatling.users",
     "query": "SELECT last(\"count\")  / $rpsHack FROM \"gatling\" WHERE (\"request\" =~ /^$request$/) AND $timeFilter GROUP BY time(10s), \"simulation\", \"group1\", \"group2\", \"status\", \"request\", \"simulation\"",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    }
   ]
  },
  {
   "title": "Active users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$g" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "gatling.users",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    }
   ]
  },
  {
   "title": "Finished users",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_simulation ::  $tag_request",
     "groupBy": [
      { "params": [ "$g" ], "type": "time" }
     ],
     "measurement": "gatling.users",
     "query": "SELECT last(\"count\")  / $rpsHack FROM \"gatling\" WHERE (\"request\" =~ /^$request$/) AND $timeFilter GROUP BY time(10s), \"simulation\", \"group1\", \"group2\", \"status\", \"request\", \"simulation\"",
     "select": [
      [
       { "params": [ "done" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    }
   ]
  },
  {
   "title": "Latency 95th (ok only)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 4 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$g" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    }
   ]
  },
  {
   "title": "RPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "gatling",
     "query": "SELECT last(\"count\") FROM \"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'all') AND $timeFilter GROUP BY time($g)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    }
   ]
  },
  {
   "title": "Latencies: Percentiles (ok only)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$g" ], "type": "time" }
     ],
     "measurement": "gatling",
     "query": "SELECT \"percentiles50\" FROM \"gatling\" WHERE \"request\" = 'allRequests' AND \"status\" = 'ok' AND $timeFilter",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "percentile 95" ], "type": "alias" }
      ],
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    }
   ]
  },
  {
   "title": "Statistics (ok only)",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT min(\"min\") AS \"Min\", max(\"max\") AS \"Max\", mean(\"mean\") AS \"Mean\", percentile(\"percentiles95\", 95) AS \"95th pct\" FROM \"gatling\" WHERE (\"status\" = 'all' AND \"request\" != 'allRequests') AND $timeFilter GROUP BY \"request\"\n",
     "select": [
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "Min" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Mean" ], "type": "alias" }
      ],
      [
       { "params": [ "percentiles95" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       },
       { "params": [ "95th pct" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "request", "operator": "!=", "value": "allRequests" }
     ]
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "reqps", "label": "Number of requests" }
   ],
   "targets": [
    {
     "alias": "RPS",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "gatling",
     "query": "SELECT last(\"count\") FROM \"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'all') AND $timeFilter GROUP BY time($g)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors (count)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "error",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$g" ], "type": "time" }
     ],
     "measurement": "gatling",
     "query": "SELECT count(\"min\") FROM \"gatling\" WHERE (\"request\" =~ /^$request$/ AND \"status\" = 'ko' AND \"simulation\" =~ /^$simulation$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time Distribution (ok)",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "measurement": "gatling",
       "query": "SELECT last(\"count\")  / $rpsHack FROM \"gatling\" WHERE (\"request\" =~ /^$request$/) AND $timeFilter GROUP BY time(10s), \"simulation\", \"group1\", \"group2\", \"status\", \"request\", \"simulation\"",
       "select": [
        [
         { "params": [ "percentiles95" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "request", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      }
     ]
    },
    {
     "title": "Response Time Distribution (ko)",
     "type": "graph",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_status",
       "groupBy": [
        { "params": [ "status" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT last(\"count\")  / $rpsHack FROM \"gatling\" WHERE (\"request\" =~ /^$request$/) AND $timeFilter GROUP BY time(10s), \"simulation\", \"group1\", \"group2\", \"status\", \"request\", \"simulation\"",
       "select": [
        [
         { "params": [ "percentiles95" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" },
        { "condition": "AND", "key": "request", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      }
     ]
    },
    {
     "title": "Response Time Percentiles over Time (OK)",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "ms", "label": "Response Time" }
     ],
     "targets": [
      {
       "alias": "$tag_simulation::$col",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "simulation" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "query": "SELECT \"percentiles50\" FROM \"gatling\" WHERE \"request\" = 'allRequests' AND \"status\" = 'ok' AND $timeFilter",
       "select": [
        [
         { "params": [ "percentiles50" ], "type": "field" },
         { "params": [ "50" ], "type": "percentile" },
         { "params": [ "50%" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles95" ], "type": "field" },
         { "params": [ "95" ], "type": "percentile" },
         { "params": [ "95%" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles99" ], "type": "field" },
         { "params": [ "99" ], "type": "percentile" },
         { "params": [ "99%" ], "type": "alias" }
        ],
        [
         { "params": [ "max" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "max" ], "type": "alias" }
        ],
        [
         { "params": [ "percentiles75" ], "type": "field" },
         { "params": [ "75" ], "type": "percentile" },
         { "params": [ "75%" ], "type": "alias" }
        ],
        [
         { "params": [ "min" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         },
         { "params": [ "min" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "request", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      }
     ]
    },
    {
     "title": "Individual Request mean time (all statuses)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_simulation :: $tag_request",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "request" ], "type": "tag" },
        { "params": [ "simulation" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
        { "condition": "AND", "key": "request", "operator": "!=", "value": "allRequests" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Individual Request mean time (error/fail statuses)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_simulation :: $tag_request",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "request" ], "type": "tag" },
        { "params": [ "simulation" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      }
     ]
    },
    {
     "title": "Individual Request count (fail/error statuses)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_simulation :: $tag_request",
       "groupBy": [
        { "params": [ "$g" ], "type": "time" },
        { "params": [ "request" ], "type": "tag" },
        { "params": [ "simulation" ], "type": "tag" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         }
        ]
       ],
       "tags": [
        { "key": "status", "operator": "=", "value": "ko" },
        { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}